POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"mofffo@hotmail.com",
  "password":"123456789",
  "type":"csr"

}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"momo@hotmail.com",
  "password":"123456789"

}
###
GET  http://localhost:3000/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkZG1AaG90bWFpbC5jb20iLCJpYXQiOjE2OTAxNTI4MjUsImV4cCI6MTY5MDE1NjQyNX0.yjAk-bIHVgBW-51wWTxU5V-Dg-t_Do2X-U5FYL5clHI