POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"sddm@hotmail.com",
  "password":"fff",
  "type":"cs"

}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email":"sddm@hotmail.com",
  "password":"fff"

}
###
GET  http://localhost:3000/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNkZG1AaG90bWFpbC5jb20iLCJpYXQiOjE2ODk5NzMxMzIsImV4cCI6MTY4OTk3NjczMn0.83kO5HIo1UQqLDTH3ar7IZx9C7dISTMS-TM9l5HUFng